name: SHAPEAlaska
favicon: null
layout_spectrum: 1
typography_spectrum: 0.2404
title: Alaska Society for Health and Physical Education
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#cf0000'
    - '#cccccc'
    - '#6f6f6e'
  brandStrength: 1
  lightness: 0.375
  saturation: 1
  rhythmicContrast: 0.5
purpose:
  - name: null
    item: null
    url: null
