name: SHAPEAlaska
favicon: null
layout_spectrum: 1
typography_spectrum: 0.17863
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#010080'
    - '#cdb3b5'
    - '#346091'
    - '#aee9fa'
  brandStrength: 0.886261
  lightness: 0.796171
  saturation: 0.797297
  rhythmicContrast: 0.301801
purpose:
  - name: null
    item: null
    url: null
